// EDC 数字博物馆 · 数据源：飞书选款清单（2026-09-07 revision 43 导出，19 款）
// 字段口径与《EDC数字博物馆-首期选款清单》一致
window.EDC_ITEMS = [
 {
  "id": 1,
  "brand": "傲娇的老铁匠",
  "model": "嘉年华MEGA",
  "category": "桌面轮盘",
  "scene": "桌面·磁力联动",
  "price": "¥1999（nano小轮盘¥999）",
  "priceStatus": "已核（官方渠道）",
  "play": "铜+不锈钢，磁力耦合专利双盘联动：外圈转→内圈5倍速反向旋转，16档数字转盘",
  "heatBasis": "垂直站头号品牌+EDC SHOW展会创办方+单品GMV 300万+",
  "signals": "垂直站,展会,电商",
  "srcCount": "3",
  "signalLevel": "A级",
  "priority": "首批",
  "heat": 5,
  "market": 5,
  "categoryRep": 4,
  "uniqueness": 5,
  "priceCover": 5,
  "digitalFit": 5,
  "total": 29,
  "modelStatus": "未开始",
  "note": "镇馆之宝，数字博物馆主视觉候选",
  "icon": "🧩"
 },
 {
  "id": 2,
  "brand": "01EDC",
  "model": "基因舱",
  "category": "推牌",
  "scene": "手持·复合高端",
  "price": "PEI ¥799（限180）/钛 ¥988（限90）/海外$179起",
  "priceStatus": "已核（官方渠道）",
  "play": "直推联动旋转独创+磁吸电报夹+DUANG震感，BRRP评分9.2/五颗星",
  "heatBasis": "抖音头部测评高分+官方站海外在售",
  "signals": "垂直站,年度榜单,官方站",
  "srcCount": "3",
  "signalLevel": "A级",
  "priority": "首批",
  "heat": 5,
  "market": 4,
  "categoryRep": 4,
  "uniqueness": 5,
  "priceCover": 4,
  "digitalFit": 5,
  "total": 27,
  "modelStatus": "未开始",
  "note": "推牌复合玩法标杆，磁吸+震感双体验",
  "icon": "🃏"
 },
 {
  "id": 3,
  "brand": "玩物乐志",
  "model": "钢骨",
  "category": "推牌",
  "scene": "手持·机械磁力",
  "price": "¥599起（钛/PEI限量599）",
  "priceStatus": "已核（官方渠道）",
  "play": "中间滑块磁力撞击为核心手感，可配伴生骨/义眼",
  "heatBasis": "年度榜单+垂直站收录+二级市场溢价（一骨难求）",
  "signals": "垂直站,年度榜单,电商",
  "srcCount": "3",
  "signalLevel": "A级",
  "priority": "首批",
  "heat": 5,
  "market": 5,
  "categoryRep": 4,
  "uniqueness": 4,
  "priceCover": 4,
  "digitalFit": 4,
  "total": 26,
  "modelStatus": "未开始",
  "note": "二级市场溢价验证收藏属性",
  "icon": "🃏"
 },
 {
  "id": 4,
  "brand": "元核EDC",
  "model": "震震鼓",
  "category": "震感",
  "scene": "手持·震感解压",
  "price": "3D打印版¥55（可叠券至40+）/PEI限量¥399~435",
  "priceStatus": "已核（官方渠道）",
  "play": "正面机械叮咚+反面巴克球密集震颤，可调磁力/弹簧",
  "heatBasis": "抖音测评爆款（人手一个）+类目走量数据",
  "signals": "垂直站,年度榜单,电商",
  "srcCount": "3",
  "signalLevel": "A级",
  "priority": "首批",
  "heat": 5,
  "market": 5,
  "categoryRep": 4,
  "uniqueness": 4,
  "priceCover": 3,
  "digitalFit": 5,
  "total": 26,
  "modelStatus": "未开始",
  "note": "为App触觉震动打样的首选对象",
  "icon": "📳"
 },
 {
  "id": 5,
  "brand": "扎克实验室",
  "model": "小飞机（ZacLab）",
  "category": "推牌",
  "scene": "手持·直推",
  "price": "¥99",
  "priceStatus": "已核（社区渠道）",
  "play": "直推结构，年度评价'光靠价格就能杀穿'",
  "heatBasis": "垂直站'上架即售罄黑马'+年度最佳段落双源",
  "signals": "垂直站,年度榜单",
  "srcCount": "2",
  "signalLevel": "A级",
  "priority": "首批",
  "heat": 4,
  "market": 5,
  "categoryRep": 4,
  "uniqueness": 3,
  "priceCover": 3,
  "digitalFit": 3,
  "total": 22,
  "modelStatus": "未开始",
  "note": "低价位带代表，验证'用数据选款'的典型",
  "icon": "🃏"
 },
 {
  "id": 6,
  "brand": "PEL",
  "model": "TITA（瘦婆）",
  "category": "推牌",
  "scene": "手持·磁吸推牌",
  "price": "¥300~500档",
  "priceStatus": "待核（对比价推算）",
  "play": "磁力推牌手感标杆，B站评价'手感业界独一份'",
  "heatBasis": "B站测评+上海EDC SHOW参展+500元十佳三源",
  "signals": "展会,年度榜单,社区",
  "srcCount": "3",
  "signalLevel": "A级",
  "priority": "首批",
  "heat": 4,
  "market": 3,
  "categoryRep": 5,
  "uniqueness": 5,
  "priceCover": 4,
  "digitalFit": 4,
  "total": 25,
  "modelStatus": "未开始",
  "note": "手感标杆，值得实拍精细建模",
  "icon": "🃏"
 },
 {
  "id": 7,
  "brand": "开物KOVO",
  "model": "云闪",
  "category": "滑块",
  "scene": "手持·巴克球轨道",
  "price": "¥200+（PEI）/¥499（涟漪版大全套）",
  "priceStatus": "已核（测评渠道）",
  "play": "PEI涟漪透明窗可见机械轨道，可换中柱（PEK/POM/磁吸），弹簧珠+磁吸轨道+巴克球头尾震手复合手感",
  "heatBasis": "年度最佳巴克球+500元十佳推牌+淘宝二级市场在售",
  "signals": "年度榜单,社区,电商",
  "srcCount": "3",
  "signalLevel": "A级",
  "priority": "首批",
  "heat": 4,
  "market": 3,
  "categoryRep": 4,
  "uniqueness": 5,
  "priceCover": 3,
  "digitalFit": 5,
  "total": 24,
  "modelStatus": "F2配置化完成（模型几何/把玩/音效参数全部配置驱动，浏览器回归通过）",
  "note": "声音类进首期（任务2证据链：双源互证通过，证据从1源升3源）；涟漪版¥499",
  "icon": "🎚"
 },
 {
  "id": 8,
  "brand": "矩阵EDC",
  "model": "弹窗2.0",
  "category": "滑块",
  "scene": "手持·磁吸弹窗",
  "price": "待核（不锈钢/钛/锆三版本）",
  "priceStatus": "待核",
  "play": "直推+可活动中层结构，磁吸弹窗",
  "heatBasis": "垂直站收录+EDC DAY参展",
  "signals": "垂直站,展会",
  "srcCount": "2",
  "signalLevel": "A级",
  "priority": "首批",
  "heat": 3,
  "market": 4,
  "categoryRep": 4,
  "uniqueness": 3,
  "priceCover": 3,
  "digitalFit": 4,
  "total": 21,
  "modelStatus": "未开始",
  "note": "弹窗类玩法代表",
  "icon": "🎚"
 },
 {
  "id": 9,
  "brand": "魔山EDC",
  "model": "静音推牌",
  "category": "推牌",
  "scene": "手持·静音",
  "price": "PEI ¥99（300套）/钢¥168/钛¥268",
  "priceStatus": "已核（官方渠道）",
  "play": "双机械轨道+磁铁槽+四限位槽，上盖整体弹射Q弹回弹",
  "heatBasis": "社区'摸鱼神器'+静音=海外2025关键趋势",
  "signals": "社区,社媒",
  "srcCount": "2",
  "signalLevel": "B级",
  "priority": "首批",
  "heat": 4,
  "market": 4,
  "categoryRep": 4,
  "uniqueness": 4,
  "priceCover": 4,
  "digitalFit": 4,
  "total": 24,
  "modelStatus": "未开始",
  "note": "静音主题自带办公室/自习室场景",
  "icon": "🃏"
 },
 {
  "id": 10,
  "brand": "空山",
  "model": "烈焰 无限位推牌",
  "category": "推牌",
  "scene": "手持·花式甩牌",
  "price": "¥68~86（正版；复刻15.8~79.8）",
  "priceStatus": "已核（需防复刻）",
  "play": "8+8磁铁位N35强磁，68g全金属，无限位花式甩牌",
  "heatBasis": "电商走量+测评视觉冲击强",
  "signals": "电商,社区",
  "srcCount": "2",
  "signalLevel": "B级",
  "priority": "首批",
  "heat": 3,
  "market": 4,
  "categoryRep": 4,
  "uniqueness": 3,
  "priceCover": 4,
  "digitalFit": 4,
  "total": 22,
  "modelStatus": "未开始",
  "note": "视觉冲击适合3D动态展示，验证闭环第一候选",
  "icon": "🃏"
 },
 {
  "id": 11,
  "brand": "大雄EDC",
  "model": "胖男孩",
  "category": "陀螺",
  "scene": "桌面·复合陀螺",
  "price": "待核",
  "priceStatus": "待核",
  "play": "官方5种玩法：磁铁环+不锈钢珠+磁铁柱+8球配件",
  "heatBasis": "年度榜单陀螺篇（巴雷特相关）",
  "signals": "年度榜单",
  "srcCount": "1",
  "signalLevel": "B级",
  "priority": "首批",
  "heat": 4,
  "market": 2,
  "categoryRep": 4,
  "uniqueness": 4,
  "priceCover": 3,
  "digitalFit": 4,
  "total": 21,
  "modelStatus": "未开始",
  "note": "复合玩法陀螺代表",
  "icon": "🌀"
 },
 {
  "id": 12,
  "brand": "穿山甲EDC",
  "model": "千禧推牌",
  "category": "推牌",
  "scene": "手持·造型话题",
  "price": "¥1000+",
  "priceStatus": "已核（展会渠道）",
  "play": "软盘造型+18颗巴克球六段波浪磁力轨道阶梯式音阶，PEI+钛",
  "heatBasis": "上海/广州两展均亮相",
  "signals": "展会",
  "srcCount": "1",
  "signalLevel": "B级",
  "priority": "首批",
  "heat": 3,
  "market": 3,
  "categoryRep": 4,
  "uniqueness": 5,
  "priceCover": 5,
  "digitalFit": 4,
  "total": 24,
  "modelStatus": "未开始",
  "note": "造型话题性强，自带传播点",
  "icon": "🃏"
 },
 {
  "id": 13,
  "brand": "三合一幽灵",
  "model": "指尖陀螺",
  "category": "陀螺",
  "scene": "手持·入门走量",
  "price": "¥12.8~19.9",
  "priceStatus": "已核（电商渠道）",
  "play": "陀螺+啪啪币+机械推牌三合一",
  "heatBasis": "电商走量数据（低价爆款）",
  "signals": "电商",
  "srcCount": "1",
  "signalLevel": "B级",
  "priority": "首批",
  "heat": 3,
  "market": 4,
  "categoryRep": 3,
  "uniqueness": 3,
  "priceCover": 2,
  "digitalFit": 3,
  "total": 18,
  "modelStatus": "未开始",
  "note": "入门价格带，拉新引流位",
  "icon": "🌀"
 },
 {
  "id": 14,
  "brand": "鱼骨EDC",
  "model": "叮叮币",
  "category": "声音",
  "scene": "手持·发声",
  "price": "¥99",
  "priceStatus": "已核（电商渠道）",
  "play": "金属币摩擦发声，淘宝4.9分/4000+评价",
  "heatBasis": "淘宝高评分高评价量",
  "signals": "电商",
  "srcCount": "1",
  "signalLevel": "备选",
  "priority": "二期候选",
  "heat": 2,
  "market": 4,
  "categoryRep": 3,
  "uniqueness": 3,
  "priceCover": 2,
  "digitalFit": 2,
  "total": 16,
  "modelStatus": "未开始",
  "note": "声音类备选；社区口碑强（30块小垃圾之王），双轨高低音+弹簧珠调音，二期优先",
  "icon": "🔔"
 },
 {
  "id": 15,
  "brand": "细胞EDC",
  "model": "破坏者",
  "category": "收藏",
  "scene": "手持·收藏级",
  "price": "¥1300+（130+零件）",
  "priceStatus": "待核",
  "play": "130+零件收藏级结构，EDC DAY官方报道重点",
  "heatBasis": "EDC DAY展会官方报道",
  "signals": "展会,报道",
  "srcCount": "2",
  "signalLevel": "备选",
  "priority": "二期候选",
  "heat": 3,
  "market": 2,
  "categoryRep": 4,
  "uniqueness": 5,
  "priceCover": 4,
  "digitalFit": 4,
  "total": 22,
  "modelStatus": "未开始",
  "note": "收藏级天花板，二期可作镇馆第二件",
  "icon": "🏛"
 },
 {
  "id": 16,
  "brand": "MOT EDC",
  "model": "风铃",
  "category": "声音",
  "scene": "手持·音叉泛音",
  "price": "¥399",
  "priceStatus": "已核（官方渠道）",
  "play": "音叉泛音设计，垂直站收录",
  "heatBasis": "垂直站收录+音效类稀缺",
  "signals": "垂直站",
  "srcCount": "1",
  "signalLevel": "备选",
  "priority": "二期候选",
  "heat": 3,
  "market": 2,
  "categoryRep": 4,
  "uniqueness": 4,
  "priceCover": 3,
  "digitalFit": 4,
  "total": 20,
  "modelStatus": "未开始",
  "note": "纯音效类代表，App声音模拟储备",
  "icon": "🔔"
 },
 {
  "id": 17,
  "brand": "零努力",
  "model": "赛博核桃",
  "category": "文玩",
  "scene": "手持·盘玩",
  "price": "待核",
  "priceStatus": "待核",
  "play": "赛博核桃概念，文玩与EDC跨界",
  "heatBasis": "跨界话题性（EDC被称为'男人的赛博盘串'）",
  "signals": "社媒",
  "srcCount": "1",
  "signalLevel": "备选",
  "priority": "二期候选",
  "heat": 3,
  "market": 2,
  "categoryRep": 4,
  "uniqueness": 4,
  "priceCover": 3,
  "digitalFit": 4,
  "total": 20,
  "modelStatus": "未开始",
  "note": "文玩手串品类扩张的战略衔接款",
  "icon": "📿"
 },
 {
  "id": 18,
  "brand": "ROGUE",
  "model": "Top-B机",
  "category": "机械",
  "scene": "手持·机械",
  "price": "¥759~959",
  "priceStatus": "已核（展会渠道）",
  "play": "上海展热门机械款",
  "heatBasis": "上海EDC SHOW现场热度",
  "signals": "展会",
  "srcCount": "1",
  "signalLevel": "备选",
  "priority": "二期候选",
  "heat": 3,
  "market": 2,
  "categoryRep": 3,
  "uniqueness": 3,
  "priceCover": 4,
  "digitalFit": 4,
  "total": 19,
  "modelStatus": "未开始",
  "note": "中高端机械款补充",
  "icon": "⚙️"
 },
 {
  "id": 19,
  "brand": "GD EDC",
  "model": "国风系列",
  "category": "推牌",
  "scene": "手持·国风",
  "price": "待核",
  "priceStatus": "待核",
  "play": "国风差异化设计",
  "heatBasis": "垂直站收录",
  "signals": "垂直站",
  "srcCount": "1",
  "signalLevel": "备选",
  "priority": "二期候选",
  "heat": 2,
  "market": 2,
  "categoryRep": 3,
  "uniqueness": 3,
  "priceCover": 3,
  "digitalFit": 3,
  "total": 16,
  "modelStatus": "未开始",
  "note": "国风差异化，出海内容储备",
  "icon": "🃏"
 }
];
